#define NOMINMAX

#include "devemu_ps2_keyboard.h"

#include "../../core/cerf_emulator.h"
#include "../../core/log.h"
#include "../../host/keyboard_input.h"
#include "../../peripherals/peripheral_dispatcher.h"
#include "../../socs/irq_controller.h"
#include "../board_detector.h"

REGISTER_SERVICE(DevEmuPs2Keyboard);

namespace {

/* Register offsets relative to base 0x59000020. The six SPI register
   groups (SPCON / SPSTA / SPPIN / SPPRE / SPTDAT / SPRDAT) live at
   4-byte stride. */
constexpr uint32_t kRegSpcon  = 0x00u;
constexpr uint32_t kRegSpsta  = 0x04u;
constexpr uint32_t kRegSppin  = 0x08u;
constexpr uint32_t kRegSppre  = 0x0Cu;
constexpr uint32_t kRegSptdat = 0x10u;
constexpr uint32_t kRegSprdat = 0x14u;

/* SPSTA bit 0 — Transfer Ready Flag. Re-asserted on every SPTDAT
   write per the BSP's IOSPI1::WriteWord. */
constexpr uint32_t kSpstaRedy = 0x1u;

/* SMOD field in SPCON: bits 5:6 per the S3C2410A user manual chapter
   22 ("SPI"). The BSP keyboard driver enables interrupt mode by
   writing SMOD=1; in any other mode the keyboard ring is gated off
   (matches IOSPI1::EnqueueKey's "if (SPCON.Bits.SMOD != 1) return"). */
constexpr uint32_t kSpconSmodMask  = 0x60u;
constexpr uint32_t kSpconSmodShift = 5;
constexpr uint32_t kSpconSmodIntMode = 1;

/* IRQ_EINT1 = 1 from the BSP's s3c2410x_intr.h — the external
   interrupt line the BSP wires its virtual PS/2 keyboard controller
   to. Raised on every key enqueue (and re-raised inside SPRDAT-pop
   when more scancodes remain). */
constexpr int kIrqEint1 = 1;

/* PS/2 scancode make/break bit: OR into the byte to signal key-up. */
constexpr uint8_t kScKeyUp   = 0x80u;
constexpr uint8_t kScKeyDown = 0x00u;

constexpr uint8_t kVkHyphen   = 0xBD;
constexpr uint8_t kVkMatrixFn = 0xC0;
constexpr uint8_t kVkShift    = 0x10;
constexpr uint8_t kVkLShift   = 0xA0;

/* VK → PS/2 scancode table — verbatim from the BSP's vktoscan.c
   (auto-generated by ScanToVK on 2005-04-25). Indexed by Win32 vk;
   a non-zero entry is a direct mapping, a zero entry routes the key
   through the function-key / numlock helper tables. */
constexpr uint8_t kVkToScTable[256] = {
    /* 0x00-0x0F */ 0x61, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x69, 0x0B, 0x00, 0x00, 0x00, 0x5A, 0x00, 0x00,
    /* 0x10-0x1F */ 0x12, 0x19, 0x01, 0x00, 0x2C, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x29, 0x00, 0x00, 0x00, 0x00,
    /* 0x20-0x2F */ 0x6E, 0x00, 0x00, 0x00, 0x00, 0x6D, 0x6C, 0x6F,
                    0x6A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2A, 0x00,
    /* 0x30-0x3F */ 0x49, 0x31, 0x39, 0x2F, 0x37, 0x3F, 0x47, 0x4F,
                    0x57, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 0x40-0x4F */ 0x00, 0x0D, 0x3E, 0x2E, 0x35, 0x3B, 0x3D, 0x45,
                    0x4D, 0x52, 0x55, 0x44, 0x4C, 0x4E, 0x46, 0x4B,
    /* 0x50-0x5F */ 0x53, 0x2B, 0x43, 0x2D, 0x3A, 0x4A, 0x36, 0x33,
                    0x0E, 0x42, 0x0C, 0x60, 0x5F, 0x00, 0x00, 0x00,
    /* 0x60-0x6F */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 0x70-0x7F */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 0x80-0x8F */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 0x90-0x9F */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 0xA0-0xAF */ 0x12, 0x62, 0x19, 0x19, 0x01, 0x01, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 0xB0-0xBF */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x54, 0x59, 0x56, 0x51, 0x5E, 0x5D,
    /* 0xC0-0xCF */ 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 0xD0-0xDF */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x5B, 0x0A, 0x6B, 0x5C, 0x00,
    /* 0xE0-0xEF */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 0xF0-0xFF */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

/* Helper tables — also verbatim from vktoscan.c. Each entry is
   (host_vk → guest_vk); the guest_vk then re-enters kVkToScTable to
   produce the actual scancode, wrapped with Fn-down/Fn-up. */
struct VkMap { uint8_t host_vk; uint8_t guest_vk; };

constexpr VkMap kVkMapFn[21] = {
    { 0x70, 0x31 }, { 0x71, 0x32 }, { 0x72, 0x33 }, { 0x73, 0x34 },
    { 0x74, 0x35 }, { 0x75, 0x36 }, { 0x76, 0x37 }, { 0x77, 0x38 },
    { 0x78, 0x39 }, { 0x79, 0x30 }, { 0x90, 0xBD }, { 0x03, 0xBB },
    { 0x2D, 0x50 }, { 0x13, 0xDB }, { 0x91, 0xDD }, { 0x2C, 0xBA },
    { 0x2C, 0xDE }, { 0x24, 0x25 }, { 0x21, 0x26 }, { 0x22, 0x28 },
    { 0x23, 0x27 },
};

constexpr VkMap kVkMapNumLock[15] = {
    { 0x67, 0x37 }, { 0x68, 0x38 }, { 0x69, 0x39 }, { 0x6A, 0x30 },
    { 0x64, 0x55 }, { 0x65, 0x49 }, { 0x66, 0x4F }, { 0x6D, 0x50 },
    { 0x61, 0x4A }, { 0x62, 0x4B }, { 0x63, 0x4C }, { 0x6B, 0xBA },
    { 0x60, 0x4D }, { 0x6E, 0xBE }, { 0x6F, 0xBF },
};

/* Adapter connecting HostWindow's KeyboardInput dispatch to the
   DevEmuPs2Keyboard peripheral. Anonymous-namespaced — its only role
   is to occupy the KeyboardInput slot and forward calls; nothing
   outside this .cpp names the type. */
class DevEmuKeyboardInput : public KeyboardInput {
public:
    using KeyboardInput::KeyboardInput;
    bool ShouldRegister() override {
        auto* bd = emu_.TryGet<BoardDetector>();
        return bd && bd->GetBoard() == Board::Smdk2410DevEmu;
    }
    void OnHostKey(uint8_t vk, bool key_up) override {
        emu_.Get<DevEmuPs2Keyboard>().OnHostKey(vk, key_up);
    }
};

}  /* namespace */

REGISTER_SERVICE_AS(DevEmuKeyboardInput, KeyboardInput);

bool DevEmuPs2Keyboard::ShouldRegister() {
    auto* bd = emu_.TryGet<BoardDetector>();
    return bd && bd->GetBoard() == Board::Smdk2410DevEmu;
}

void DevEmuPs2Keyboard::OnReady() {
    emu_.Get<PeripheralDispatcher>().Register(this);
}

uint32_t DevEmuPs2Keyboard::ReadWord(uint32_t addr) {
    const uint32_t off = addr - MmioBase();
    uint32_t value = 0;
    bool     keys_remain_after_pop = false;
    {
        std::lock_guard<std::mutex> lk(state_mutex_);
        switch (off) {
            case kRegSpcon:
                value = spcon_;
                break;
            case kRegSpsta:
                value = spsta_;
                break;
            case kRegSppin:
                value = sppin_;
                break;
            case kRegSppre:
                value = sppre_;
                break;
            case kRegSptdat:
                value = sptdat_;
                break;
            case kRegSprdat:
                if (sptdat_ == 0xFF && queue_head_ != queue_tail_) {
                    sprdat_     = queue_[queue_tail_];
                    queue_tail_ = (queue_tail_ + 1) % kQueueLen;
                    keys_remain_after_pop = (queue_head_ != queue_tail_);
                } else {
                    sprdat_ = 0;
                }
                value = sprdat_;
                break;
            default:
                HaltUnsupportedAccess("ReadWord", addr, 0);  /* noreturn */
        }
    }
    /* Re-raise outside state_mutex_ — IrqController has its own lock
       and we don't want to hold ours across the call. */
    if (keys_remain_after_pop) {
        emu_.Get<IrqController>().AssertIrq(kIrqEint1);
    }
    return value;
}

void DevEmuPs2Keyboard::WriteWord(uint32_t addr, uint32_t value) {
    const uint32_t off = addr - MmioBase();
    LOG(Periph, "[Ps2Kbd] write +0x%02X = 0x%08X\n", off, value);
    std::lock_guard<std::mutex> lk(state_mutex_);
    switch (off) {
        case kRegSpcon:
            spcon_ = value;
            break;
        case kRegSpsta:
            /* Read-only on the real SPI controller; drop the write. */
            break;
        case kRegSppin:
            sppin_ = value;
            break;
        case kRegSppre:
            sppre_ = value;
            break;
        case kRegSptdat:
            sptdat_ = static_cast<uint8_t>(value);
            spsta_ |= kSpstaRedy;
            break;
        case kRegSprdat:
            sprdat_ = static_cast<uint8_t>(value);
            break;
        default:
            HaltUnsupportedAccess("WriteWord", addr, value);  /* noreturn */
    }
}

void DevEmuPs2Keyboard::EnqueueScancode(uint8_t sc) {
    bool raise = false;
    {
        std::lock_guard<std::mutex> lk(state_mutex_);
        const uint32_t smod = (spcon_ & kSpconSmodMask) >> kSpconSmodShift;
        if (smod != kSpconSmodIntMode) {
            /* Keyboard disabled by guest driver — drop the key on the
               floor, matching the BSP's IOSPI1::EnqueueKey behavior. */
            return;
        }
        queue_[queue_head_] = sc;
        queue_head_ = (queue_head_ + 1) % kQueueLen;
        /* No overflow check — head wrapping into tail silently
           overwrites the oldest pending scancode, also matching the
           BSP's behavior. */
        raise = true;
    }
    if (raise) {
        LOG(Periph, "[Ps2Kbd] enqueue 0x%02X, raising EINT1\n", sc);
        emu_.Get<IrqController>().AssertIrq(kIrqEint1);
    }
}

void DevEmuPs2Keyboard::OnHostKey(uint8_t vk, bool key_up) {
    /* Win32 reports VK_SHIFT (0x10) for either L or R shift; the
       BSP table only has scancodes at the VK_LSHIFT slot (0xA0), so
       remap before lookup. */
    if (vk == kVkShift) vk = kVkLShift;

    const uint8_t key_state = key_up ? kScKeyUp : kScKeyDown;

    /* Direct mapping — vast majority of keys land here. */
    if (kVkToScTable[vk] != 0) {
        EnqueueScancode((uint8_t)(kVkToScTable[vk] | key_state));
        return;
    }

    /* No direct match — try function-key map first, then numlock map. */
    uint8_t mapped_vk        = 0;
    bool    from_numlock_map = false;
    for (const auto& m : kVkMapFn) {
        if (m.host_vk == vk) { mapped_vk = m.guest_vk; break; }
    }
    if (mapped_vk == 0) {
        for (const auto& m : kVkMapNumLock) {
            if (m.host_vk == vk) {
                mapped_vk        = m.guest_vk;
                from_numlock_map = true;
                break;
            }
        }
        /* If we matched via the numlock table and the guest currently
           has NumLock on, flip it off first with the "Fn + - down + -
           up + Fn" sequence. Only fires once because we update
           num_lock_state_ below. */
        if (from_numlock_map && mapped_vk != 0 && num_lock_state_) {
            EnqueueScancode((uint8_t)(kVkToScTable[kVkMatrixFn] | kScKeyDown));
            EnqueueScancode((uint8_t)(kVkToScTable[kVkHyphen]   | kScKeyDown));
            EnqueueScancode((uint8_t)(kVkToScTable[kVkHyphen]   | kScKeyUp));
            EnqueueScancode((uint8_t)(kVkToScTable[kVkMatrixFn] | kScKeyUp));
            num_lock_state_ = false;
        }
    }

    if (mapped_vk == 0) {
        /* No mapping found anywhere; drop silently (matches BSP). */
        return;
    }

    /* Toggle our shadow numlock state on a numlock-key down event
       (mirrors the BSP's "if (pvkMapMatch == VK_HYPHEN && KeyUpDown
       == 0) m_NumLockState = !m_NumLockState"). */
    if (mapped_vk == kVkHyphen && !key_up) {
        num_lock_state_ = !num_lock_state_;
    }

    /* Send the wrapped sequence: Fn-down + mapped key + Fn-up. */
    EnqueueScancode((uint8_t)(kVkToScTable[kVkMatrixFn] | kScKeyDown));
    EnqueueScancode((uint8_t)(kVkToScTable[mapped_vk]   | key_state));
    EnqueueScancode((uint8_t)(kVkToScTable[kVkMatrixFn] | kScKeyUp));
}
