#pragma once

#include <windows.h>
#include "include/ddraw_ce6.h"

extern "C" DWORD WINAPI DDGPECreateSurface(Ce6_DDHAL_CREATESURFACEDATA* pd);
extern "C" DWORD WINAPI DDGPECanCreateSurface(Ce6_DDHAL_CANCREATESURFACEDATA* pd);
extern "C" DWORD WINAPI DDGPEDestroySurface(Ce6_DDHAL_DESTROYSURFACEDATA* pd);
extern "C" DWORD WINAPI DDGPEFlip(Ce6_DDHAL_FLIPDATA* pd);
extern "C" DWORD WINAPI DDGPELock(Ce6_DDHAL_LOCKDATA* pd);
extern "C" DWORD WINAPI DDGPEUnlock(Ce6_DDHAL_UNLOCKDATA* pd);
extern "C" DWORD WINAPI DDGPESetColorKey(Ce6_DDHAL_SETCOLORKEYDATA* pd);
extern "C" DWORD WINAPI DDGPEGetFlipStatus(Ce6_DDHAL_GETFLIPSTATUSDATA* pd);
extern "C" DWORD WINAPI DDGPESetPalette(Ce6_DDHAL_SETPALETTEDATA* pd);
extern "C" DWORD WINAPI DDGPEWaitForVerticalBlank(Ce6_DDHAL_WAITFORVERTICALBLANKDATA* pd);
extern "C" DWORD WINAPI DDGPECreatePalette(Ce6_DDHAL_CREATEPALETTEDATA* pd);
