/* WinCE build system LOC_* macro definitions (US English / LCID 0x0409).
   Resolved at import time for .reg files from the platform SDK.
   Values sourced from INTLTRNS/0409/*.str in the WinCE 5.0 Platform Builder. */
#pragma once

struct LocMacro { const char* name; const char* str_val; uint32_t dw_val; };
static const LocMacro loc_macros[] = {
    /* cebase.str */
    {"LOC_DEFAULTDEVICENAME",    "WindowsCE", 0},
    {"LOC_DEFAULTDEVICEDESC",    "WindowsCE Device", 0},
    /* common.str — locale & system */
    {"LOC_LCID",                 nullptr, 0x0409},
    {"LOC_ACP",                  nullptr, 0x04e4},
    {"LOC_CONSOLEFONTNAME",      "Courier New", 0},
    {"LOC_CONSOLEFONTSIZE",      nullptr, 8},
    {"LOC_CONSOLEPAINTFIX",      nullptr, 0},
    {"LOC_MENUBARFONTWEIGHT",    nullptr, 0x2BC},
    {"LOC_BUTTONFONTWEIGHT",     nullptr, 0x2BC},
    {"LOC_HKL_DEFAULT",          "00000409", 0},
    {"LOC_KEYBOARD",             "Keyboard", 0},
    {"LOC_DEFAULT_TIMEZONE",     "Pacific Standard Time", 0},
    /* common.str — paths */
    {"LOC_PATH_APPDATA",         "\\Application Data", 0},
    {"LOC_PATH_DESKTOP",         "\\Windows\\Desktop", 0},
    {"LOC_PATH_FAVORITES",       "\\Windows\\Favorites", 0},
    {"LOC_PATH_FONTS",           "\\Windows\\Fonts", 0},
    {"LOC_PATH_MYDOCUMENTS",     "\\My Documents", 0},
    {"LOC_PATH_PROGRAMFILES",    "\\Program Files", 0},
    {"LOC_PATH_PROGRAMS",        "\\Windows\\Programs", 0},
    {"LOC_PATH_RECENT",          "\\Windows\\Recent", 0},
    {"LOC_PATH_STARTUP",         "\\Windows\\StartUp", 0},
    {"LOC_PATH_WINDOWS",         "\\Windows", 0},
    /* common.str — storage folders */
    {"LOC_STORE_DEFAULT_FOLDER", "Mounted Volume", 0},
    {"LOC_STORE_PCMCIA_FOLDER",  "Storage Card", 0},
    {"LOC_STORE_HD_FOLDER",      "Hard Disk", 0},
    {"LOC_STORE_CD_FOLDER",      "CDROM Drive", 0},
    {"LOC_STORE_FLOPPY_FOLDER",  "Floppy Drive", 0},
    {"LOC_STORE_DOC_FOLDER",     "DiskOnChip", 0},
    {"LOC_STORE_RFA_FOLDER",     "RFA Disk", 0},
    /* common.str — dialing locations */
    {"LOC_HOMEAREACODE",         "425", 0},
    {"LOC_HOMECOUNTRYCODE",      "1", 0},
    {"LOC_HOMECWCODE",           " ", 0},
    {"LOC_HOMELOCATIONNAME",     "Home", 0},
    {"LOC_HOMELOCALFMT",         "G", 0},
    {"LOC_HOMELDFMT",            "1FG", 0},
    {"LOC_HOMEINTNTLFMT",        "011,EFG", 0},
    {"LOC_HOMEOPTIONS",          "0", 0},
    {"LOC_WORKAREACODE",         "425", 0},
    {"LOC_WORKCOUNTRYCODE",      "1", 0},
    {"LOC_WORKCWCODE",           " ", 0},
    {"LOC_WORKLOCATIONNAME",     "Work", 0},
    {"LOC_WORKLOCALFMT",         "9,G", 0},
    {"LOC_WORKLDFMT",            "9,1FG", 0},
    {"LOC_WORKINTNTLFMT",        "9,011,EFG", 0},
    {"LOC_WORKOPTIONS",          "0", 0},
    /* common.str — friendly device names */
    {"LOC_FRIENDLYHAYESCOMPAT",      "Hayes Compatible on COM1:", 0},
    {"LOC_FRIENDLYHAYESFAX",         "Hayes 28.8 + Fax", 0},
    {"LOC_FRIENDLYMEGAHERTZ",        "Megahertz 28.8", 0},
    {"LOC_FRIENDLYMEGAHERTZCELL",    "Megahertz 28.8 Cellular", 0},
    {"LOC_FRIENDLYMEGAHERTZCRUISE",  "Megahertz Cruise Card 28.8", 0},
    {"LOC_FRIENDLYMEGAHERTZ144",     "Megahertz 14.4", 0},
    {"LOC_FRIENDLYSPORTSTER288",     "US Robotics Sportster 28.8", 0},
    {"LOC_FRIENDLYPROCLASS288",      "US Robotics Pro Class 28.8", 0},
    {"LOC_FRIENDLYXIRCOM336",        "Xircom 33.6", 0},
    {"LOC_FRIENDLYXIRCOMETHER336",   "Xircom Ether Modem 33.6", 0},
    {"LOC_FRIENDLYMOTOMONTANA288",   "Motorola Montana 28.8", 0},
    {"LOC_FRIENDLYMOTOPOWER144",     "Motorola Power 14.4", 0},
    {"LOC_FRIENDLYNE2000COMPAT",     "NE2000 Compatible Ethernet Driver", 0},
    {"LOC_FRIENDLYVMINI",            "Microsoft null Ethernet Miniport Driver", 0},
    {"LOC_FRIENDLYRNDISHOST",        "Remote-NDIS Host", 0},
    {"LOC_FRIENDLYMBRIDGE",          "Microsoft Mac Bridge Miniport", 0},
    {"LOC_FRIENDLYASYNCMAC",         "AsyncMac NDISWAN Miniport", 0},
    {"LOC_FRIENDLYRTL8139",          "Realtek RTL8139 based Fast Ethernet Driver", 0},
    /* ie.str — codepage descriptions */
    {"LOC_DESCRIPTION_852",      "Central European (DOS)", 0},
    {"LOC_DESCRIPTION_866",      "Cyrillic Alphabet (DOS)", 0},
    {"LOC_DESCRIPTION_932",      "Japanese (Shift-JIS)", 0},
    {"LOC_DESCRIPTION_1200",     "Universal Alphabet", 0},
    {"LOC_DESCRIPTION_1201",     "Universal Alphabet (Big-Endian)", 0},
    {"LOC_DESCRIPTION_1250",     "Central European Alphabet (Windows)", 0},
    {"LOC_DESCRIPTION_1251",     "Cyrillic Alphabet (Windows)", 0},
    {"LOC_DESCRIPTION_1252",     "Western Alphabet", 0},
    {"LOC_DESCRIPTION_1253",     "Greek Alphabet (Windows)", 0},
    {"LOC_DESCRIPTION_1254",     "Turkish Alphabet", 0},
    {"LOC_DESCRIPTION_1257",     "Baltic Alphabet (Windows)", 0},
    {"LOC_DESCRIPTION_20866",    "Cyrillic Alphabet (KOI8-R)", 0},
    {"LOC_DESCRIPTION_21866",    "Ukrainian Alphabet (KOI8-RU)", 0},
    {"LOC_DESCRIPTION_28592",    "Central European Alphabet (ISO)", 0},
    {"LOC_DESCRIPTION_28593",    "Latin 3 Alphabet (ISO)", 0},
    {"LOC_DESCRIPTION_28594",    "Baltic Alphabet (ISO)", 0},
    {"LOC_DESCRIPTION_28595",    "Cyrillic Alphabet (ISO)", 0},
    {"LOC_DESCRIPTION_28597",    "Greek Alphabet (ISO)", 0},
    {"LOC_DESCRIPTION_50000",    "User Defined", 0},
    {"LOC_DESCRIPTION_50220",    "Japanese (JIS)", 0},
    {"LOC_DESCRIPTION_50221",    "Japanese (JIS-Allow 1 byte Kana, ESC)", 0},
    {"LOC_DESCRIPTION_50222",    "Japanese (JIS-Allow 1 byte Kana, SIO)", 0},
    {"LOC_DESCRIPTION_50932",    "Japanese (Auto Select)", 0},
    {"LOC_DESCRIPTION_51932",    "Japanese (EUC)", 0},
    {"LOC_DESCRIPTION_65000",    "Universal Alphabet (UTF-7)", 0},
    {"LOC_DESCRIPTION_65001",    "Universal Alphabet (UTF-8)", 0},
    /* ie.str — file type names */
    {"LOC_HTMLFILE",             "HTML Document", 0},
    {"LOC_URLFILE",              "URL:File Protocol", 0},
    {"LOC_URLHTTP",              "URL:HyperText Transfer Protocol", 0},
    {"LOC_URLHTTPS",             "URL:HyperText Transfer Protocol with Privacy", 0},
    {"LOC_URLFTP",               "URL:File Transfer Protocol", 0},
    {"LOC_PAGEHEADER",           "&w&bPage &p of &P", 0},
    /* wceshellfe.str — shell display names */
    {"LOC_RECYCLEBINDISPLAY",    "Recycle Bin", 0},
    {"LOC_MYCOMPUTERDISPLAY",    "My Computer", 0},
    {"LOC_DATABASEDISPLAY",      "Databases", 0},
    {"LOC_STARTPAGE",            "file:///windows/default.htm", 0},
    {"LOC_SEARCHPAGE",           "http://www.msn.com/access/allinone.htm", 0},
    {"LOC_SEARCHURL",            "http://home.microsoft.com/access/autosearch.asp?p=%s", 0},
    {"LOC_APPLICATION",          "Application", 0},
    {"LOC_HTMLDOCUMENT",         "HTML Document", 0},
    {"LOC_GIFIMAGE",             "GIF Image", 0},
    {"LOC_BMPIMAGE",             "Bitmap Image", 0},
    {"LOC_JPEGIMAGE",            "JPEG Image", 0},
    {"LOC_XBMIMAGE",             "XBM Image", 0},
    {"LOC_URLLOCATION",          "URL Location", 0},
    {"LOC_HELPFILE",             "Help File", 0},
    {"LOC_DLLFILE",              "Application Extension", 0},
    {"LOC_TTFFILE",              "TrueType Font file", 0},
    {"LOC_CPLFILE",              "Control Panel extension", 0},
    {"LOC_WAVFILE",              "Wave Sound", 0},
    {"LOC_NOSOUNDS",             "No Sounds", 0},
    {"LOC_ALLSOUNDS",            "All Sounds", 0},
    {"LOC_DEFAULTSOUNDS",        "Windows CE Default", 0},
    /* wceshellfe.str — color scheme names */
    {"LOC_SCHEME_STANDARD",      "Windows Standard", 0},
    {"LOC_SCHEME_WHEAT",         "Wheat", 0},
    {"LOC_SCHEME_MARINE",        "Marine", 0},
    {"LOC_SCHEME_ROSE",          "Rose", 0},
    {"LOC_SCHEME_BRICK",         "Brick", 0},
    {"LOC_SCHEME_DESERT",        "Desert", 0},
    {"LOC_SCHEME_EGGPLANT",      "Eggplant", 0},
    {"LOC_SCHEME_HCBLACK",       "High Contrast Black", 0},
    {"LOC_SCHEME_HCWHITE",       "High Contrast White", 0},
    {"LOC_SCHEME_LILAC",         "Lilac", 0},
    {"LOC_SCHEME_MAPLE",         "Maple", 0},
    {"LOC_SCHEME_SPRUCE",        "Spruce", 0},
    {"LOC_SCHEME_STORM",         "Storm", 0},
    /* rdp.str */
    {"LOC_RDPCONNECTION",        "Remote Desktop Connection", 0},
    /* viewers.str */
    {"LOC_DOC",                  "Microsoft Word Document", 0},
    {"LOC_XLS",                  "Microsoft Excel Worksheet", 0},
    {"LOC_PPT",                  "Microsoft PowerPoint Presentation", 0},
    {"LOC_ACROBAT",              "Adobe Acrobat Document", 0},
    {"LOC_VGIFIMAGE",            "GIF Image", 0},
    {"LOC_VJPEGIMAGE",           "JPEG Image", 0},
    {"LOC_VPNGIMAGE",            "PNG Image", 0},
    {"LOC_VBMPIMAGE",            "Bitmap Image", 0},
    /* wceappsfe.str */
    {"LOC_MAIL_TRANSPORT",           "ActiveSync", 0},
    {"LOC_PWD_REG_READWORD",         "Word Documents (*.doc)", 0},
    {"LOC_PWD_REG_WRITEWORD97",      "Word 97 Document (*.doc)", 0},
    {"LOC_PWD_REG_WRITEWORD95",      "Word 6.0/95 Document (*.doc)", 0},
    {"LOC_PWD_REG_READWORDTEMPLATE",     "Word Templates (*.dot)", 0},
    {"LOC_PWD_REG_WRITEWORD97TEMPLATE",  "Word 97 Template (*.dot)", 0},
    {"LOC_PWD_REG_WRITEWORD95TEMPLATE",  "Word 6.0/95 Template (*.dot)", 0},
    {"LOC_PWORDDOCUMENT",           "Pocket Word Document", 0},
    {"LOC_WORDDOCUMENT",            "Word Document", 0},
    {"LOC_WORDTEMPLATE",             "Word Template", 0},
    {"LOC_RTFDOCUMENT",              "Rich Text Document", 0},
    {"LOC_PWORDTEMPLATE",            "Pocket Word Template", 0},
    {"LOC_TEXTDOCUMENT",             "Text Document", 0},
    {"LOC_PROGRAMFILES_DIR",         "Program Files", 0},
    {"LOC_OFFICE_DIR",               "Office", 0},
    {"LOC_TEMPLATES_DIR",            "Templates", 0},
    {"LOC_COMMUNICATION_DIR",        "Communication", 0},
    {"LOC_POUTLOOK_DIR",             "Inbox", 0},
    {"LOC_MAILATTACHMENTS_DIR",      "Mail Attachments", 0},
    {"LOC_LARGEMAILMESSAGE_DIR",     "Large Mail Messages", 0},
    {"LOC_PMAIL_EXE",                "\\windows\\pmail.exe", 0},
};
