#!/usr/bin/env python3
"""Bake cerf/assets/uart_boot_bar.png into cerf/host/uart_boot_bar_data.h."""

import sys
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parent.parent
PNG  = REPO / "cerf" / "assets" / "uart_boot_bar.png"
OUT  = REPO / "cerf" / "host" / "uart_boot_bar_data.h"


def main() -> int:
    img = Image.open(PNG).convert("RGBA")
    w, h = img.size

    pixels = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = img.getpixel((x, y))
            pixels.append((a << 24) | (r << 16) | (g << 8) | b)

    lines = [
        "// generated by tools/gen_uart_boot_bar.py",
        "",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        f"constexpr uint32_t kUartBootBarWidth  = {w};",
        f"constexpr uint32_t kUartBootBarHeight = {h};",
        "",
        "constexpr uint32_t kUartBootBarPixels"
        "[kUartBootBarWidth * kUartBootBarHeight] = {",
    ]

    per_line = 8
    for y in range(h):
        row = pixels[y * w:(y + 1) * w]
        for i in range(0, len(row), per_line):
            chunk = row[i:i + per_line]
            text = ", ".join(f"0x{p:08X}" for p in chunk)
            comma = "," if (y * w + i + len(chunk)) < len(pixels) else ""
            lines.append(f"    {text}{comma}")
        if y + 1 < h:
            lines.append("")
    lines.append("};")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({w}x{h})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
